name: rpc crate release

on:
  release:
    types: [created]
    tags:
      - rpc-v*
  push:
  pull_request:
  workflow_run:
    workflows:
      - "Sanity Check codebase"
      - "Integration testing"
    branches: [ master ]
    types:
      - completed

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          #registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          path: './rpc'
          ignore-unpublished-changes: true
          check-repo: ${{ github.event_name == 'push' }}
          dry-run: ${{ github.event_name == 'push' }}